development:
  adapter: postgresql
  encoding: unicode
  database: sfai_development
  pool: 5

production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false

production:
  adapter: postgresql
  statement_limit: 200
